spring:
    application:
        name: selforganizer
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/organizerdb
        username: root
    data:
        jpa:
            repositories:
                enabled: true
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: validate
flyway:
    locations: db/migration
    baseline-on-migrate: true
project:
    cors:
        ui-origin: http://localhost:3000
        allow-credentials: true
        max-age: 3600
server:
    port: 9000